spring:
  application:
    name: spring-boot-clean-architecture-modulith-demo
  datasource:
    url: jdbc:h2:mem:modulith-shop;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: false

server:
  port: 8080
